### ISSUE TITLE
problem with antidotec_counter when running dialyzer

### ISSUE THREAD

**Issue by aletomsic** [SyncFree/antidote#141]
Checking whether the PLT .local_dialyzer_plt is up-to-date...
dialyzer: Not a regular file: /Users/alek/Dropbox/PhD/code/antidote/deps/antidote_pb/ebin/antidotec_counter.beam

any clue?

**Comment by aletomsic** [comment]
Solved by checking out antidote from scratch...

**Comment by cmeiklejohn** [comment]
This problem is caused when you've built a PLT from a branch containing a certain module and then you switch and the PLT is no longer valid, because it's got a reference to something in the persistent lookup table that no longer exists in the compiled beam files.

You should fix the Makefile to remove the local PLT when running distclean and then ensure you always distclean when switching branches, else you run the risk of testing an incorrect build of Antidote. 

Reopening, please address.

**Comment by aletomsic** [comment]
I don't know what a PLT is. 
How could I solve it? I've never touched this make file.

**Comment by cmeiklejohn** [comment]
Addressed by #145.

**Comment by aletomsic** [comment]
Yesterday, I ran into the case when I am in master, I make dialyzer, no problem.
Then, I distclean, switch to another branch, there is an issue (with some code I changed).
Then, I distclean, switch to master branch again, run dialyzer, and get the same dialyzer error I got in the other branch.
