### ISSUE TITLE
multiple_dcs_test fails

### ISSUE THREAD

**Issue by Maryam81609** [SyncFree/antidote#149]
In pubsub_cert branch, I cannot understand why "multiple_dcs_test" fails when it only has parallel_writes_test ("simple_replication_test", and "failure_test" are removed)?

**Comment by Eipifi** [comment]
The test indeed fails after removing the simple_replication_test. **It also fails the exact same way on master branch**. It turns out that the issue is caused by wrong vectorclock comparison inside materializer_vnode.

parallel_writes_test sends 5 counter increments to 3 DCs, and expects all DCs to eventually see the value counter of 15. Instead, the DC returned the value of 5, even though remote updates already arrived and were stored in the log.

As the updates wre sent by the client, each DC handled its own updates and reached the counter value of 5. The last snapshot time for the counter was the commit time of the last increment operation.

When the client requested the value using a snapshot time (expecting to observe 15), the txn cordinator correctly waited until the stable snapshot reaches the specified snapshot time. Then, the object was materialized. The problem started here: 

https://github.com/SyncFree/antidote/blob/pubsub_cert/src/clocksi_materializer.erl#L121

The update operation from the remote DC was checked if it should be included in the new snapshot. The condition is that the incoming operation must not be included in the last snapshot, and that the operation commit time must be smaller than the snapshot time requested by the client.

The check is being done by the belongs_to_the_snapshot_op function here:

https://github.com/SyncFree/antidote/blob/pubsub_cert/src/materializer_vnode.erl#L295

The vectorclock comparison incorrectly fails because the last snapshot value at the receiving DC only holds the entry for the local DC (as only the local updates were processed so far). The vectorclock:le()/2 expects all the entries for all DCs to be in the vectorclocks given in the arguments. If there is an entry missing, the function returns false. This is why the updates from the remote DCs were not accepted and the read returned 5 instead of 15 - the belongs_to_the_snapshot_op function simply rejected those.

So why did the simple_replication_test "solve" the issue? The theory is that the simple_replication_test sent the updates from all DCs to all DCs with no concurrency involved (as it happens in multiple_dcs_test, where the updates are issued all at once). As a result, the list of the counter snapshots in the materializer might have been reordered (because these are weakly ordered to prevent the materializer from going through all of them on each read) in a way that prevented the materializer from getting the correct value. The theory is supported by the fact that putting 0 values for all DCs in counter snapshots by hand solved the issue. It's still a theory - if you have other ideas, please share them.

I'll make the pull request with rewritten vectorclock comparison commands.
