### ISSUE TITLE
Renaming of CRDT names

### ISSUE THREAD

**Issue by bieniusa** [SyncFree/antidote#222]
Collecting from the discussion via email:

antidote_crdt_counter 

antidote_crdt_awset

antidote_crdt_gset

antidote_crdt_reg_lww

antidote_crdt_map  ???

{update, {[map_field_update() | map_field_op()], actorordot()}}.

antidote_crdt_reg_mv

antidote_crdt_rga --> antidote_crdt_list_rga or antidote_crdt_sequence_rga  ??

**Comment by marc-shapiro** [comment]
> Le 30 sept. 2016 à 13h56, Annette Bieniusa <notifications@github.com> a écrit :
> 
> antidote_crdt_reg_lww
> antidote_crdt_reg_mv

This gives the impression that these are just two implementation variants of the same thing, which they are not.  They  are different types.  ⟹ antidote_crdt_lwwreg / mvreg

(Similar to antidote_crdt_awset/gset: you rightly didn’t call them _set_aw / _set_g because they are not just two implementation variants of set).
> antidote_crdt_rga --> antidote_crdt_list_rga or antidote_crdt_sequence_rga ??
> 

“Sequence” is slightly more general, but “list” is OK too

					Marc

**Comment by bieniusa** [comment]
@peterzeller @CBaquero Can you confirm that the renaming has been finalised on the antidote_crdt repo?

**Comment by CBaquero** [comment]
Hi, I don't think naming is stable yet, but I am in vacation in August. Would like to pay attention to this when back to work, or earlier if I grab some free time. I suggest we defer this till Sep when everyone is back and active again.

**Comment by bieniusa** [comment]
I am fine with deferring decisions till September, but I will be busy then with exams. So, I must identify and work on open tasks now ;)

**Comment by peterzeller** [comment]
Names were changed in #328
