### ISSUE TITLE
read FSMs not started when running antidote console

### ISSUE THREAD

**Issue by aletomsic** [SyncFree/antidote#224]

**Comment by tcrain** [comment]
It should be added to the documentation, but the best way to see how to start a DC is in the tests here:
https://github.com/SyncFree/antidote/blob/master/test/test_utils.erl#L240
The non-automatically processes are started here:
https://github.com/SyncFree/antidote/blob/master/src/inter_dc_manager.erl#L105

The reason why things aren't started immediately is sort of a mismatch between how Antidote was designed and how riak-core works.  By default when riak-core starts on a single node, it starts an "entire DC" on that node (all vnodes).  So for example if the config is set to have 128 vnodes, then for a 10 node cluster, before you connect the cluster you have 128 * 10 vnodes.  So then there are two main issues that can pop up if all processes are started before the 10 nodes join and commit to the ring:

1.  Antidote uses heartbeats inside and across DCs.  Even after a cluster is joined and committed, some of the old vnodes will still be running for an undetermined amount of time, which means replicated heartbeats which will break the protocol (even the tests were breaking).  The easiest and a safe way to fix this seemed to be to wait until the cluster was fully joined before starting the heartbeats.

2.  The reads fsms are designed to allow concurrency even over "hot keys".  So multiple clients can read the same key at the same time, this seemed to help with Zipfian workloads.  The problem here is that to do this the Erlang global naming protocol was used which has scalbility bottlenecks when adding a lot of names at the same time.  So if you have for example 20 reader threads per vnode then when you join the 10 node cluster you have 10*128*20 names, with many conflicts. (Note that since the names are only added during startup and after crash and that the global naming table is stored locally on each node, the hope is that after startup this won't be a scalability issue)

Note that a node that starts up after a crash will start these automatically, since the node already knows what vnodes it owns.

These issues should be revisited when intra-DC replication is added to Antidote, since these any many other things will affect the safety of the protocol, which will need to be addressed.

**Comment by aletomsic** [comment]
Thanks for the clarification. It makes sense.
Should we add an option when running antidote console that specifies we're gonna be running in a single machine, that will execute that command and start the fsms?

**Comment by aletomsic** [comment]
solved by PR #267
