### ISSUE TITLE
multiple_dcs_test hangs forever

### ISSUE THREAD

**Issue by angbrav** [SyncFree/antidote#86]
I have run all tests on master and I am not passing the multiple_dcs_test. Can anyone else try it out? When the test was added, the master branch was passing it. I am concern that some merged code might have screwed this up.

**Comment by lythq** [comment]
I have the same problem, looking at the logs I get the following error:
`[error] <0.2181.0>@inter_dc_communication_sender:propagate_sync:59 Send failed Reason:error Message: {replicate,[{0,{{'dev3@127.0.0.1',{...}},...},{dict,...},[{operation,undefined,{log_record,undefined,noop,...}}]}]}`

Did you do the following? Having the project folder as the working directory:
    make stagedevrel
    ./riak_test/bin/antidote-current.sh

**Comment by lythq** [comment]
The main problem is that `riak_core_metadata:put(?META_PREFIX, Partition, Clock)` – executed when updating the vectorclock of a partition – takes increasingly more time, until it exceeds the timeout of a connection between DCs. Since vectorclock vnodes call it, any vectorclock operation done while processing remote updates will have to wait for such duration. That will cause a timeout on the sender and raise the previous error.
Does anyone have suggestions on how to fix this?

**Comment by angbrav** [comment]
Any idea why it takes increasingly time to complete the operation?

Manuel

**Comment by deepthidevaki** [comment]
riak_core_metadata:put(?META_PREFIX, Partition, Clock)
is used to broadcast(gossip) the updated vectorclock to all vnodes. Can it
be because of too frequent updates?

On Mon, Jan 26, 2015 at 11:44 AM, Manuel Bravo <notifications@github.com>
wrote:

> Any idea why it takes increasingly time to complete the operation?
>
> Manuel
>
> > On 26 Jan 2015, at 08:53, Diogo Serra <notifications@github.com> wrote:
> >
> > The main problem is that riak_core_metadata:put(?META_PREFIX, Partition,
> Clock) – executed when updating the vectorclock of a partition – takes
> increasingly more time, until it exceeds the timeout of a connection
> between DCs. Since vectorclock vnodes call it, any vectorclock operation
> done while processing remote updates will have to wait for such duration.
> That will cause a timeout on the sender and raise the previous error.
> > Does anyone have suggestions on how to fix this?
> >
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/SyncFree/antidote/issues/86#issuecomment-71429881>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SyncFree/antidote/issues/86#issuecomment-71442715>.
>



-- 
------------------------------------------------------------------------------------------------------------------------------
“That which a man willingly shares, he keeps. That which he selfishly
keeps, he loses.”

**Comment by tcrain** [comment]
I don't know exactly how it works, but maybe it could it be the conflict
resolution?  I guess the way it is done now is by resolution on read?  So
if you have a lot of writes without reads you are getting larger and lager
data?

From
https://gist.github.com/jrwest/d290c14e1c472e562548

2.3 Conflict Resolution

Conflict resolution can be done on read or write.

On read, if the conflict is resolved, an option, allow_put, passed to get/3
 or iterator/2 controls whether or not the resolved value will be written
back to local storage and broadcast asynchronously.

On write, conflicts are resolved by passing a function instead of a new
value to put/3,4. The function is passed the list of existing values and
can use this and values captured within the closure to produce a new value
to store.

**Comment by lythq** [comment]
Thanks for the insights, after further debugging I was able to identify and fix the main problem.
There were too many vnodes, 64 by default. Each metadata change costs about 200ms, which combined greatly surpass the timeout when centralized on `riak_core_metadata_manager`.
In order to fix it I added the following to the beginning of the test, before creating the clusters:
```
    NumPartitions = rt_config:get(num_nodes),
    rt:update_app_config(all,[
        {riak_core, [{ring_creation_size, NumPartitions}]}
    ]),
```
